project:
  type: website

website:
  title: "Green Futures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: calltoaction.qmd
        text: Call to Action
      - href: regression.qmd
        text: Regression
      - href: about.qmd
        text: About
      


format:
  html:
    theme: [cosmo, styles.scss]
    # css: styles.css
    toc: true
    code-overflow: wrap
    number-sections: true
    self-contained: true
    grid:
      sidebar-width: 100px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1.5rem



